<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-OJQ7O3T" failures="2" tests="4" name="Test" time="10.043" errors="0" timestamp="2024-01-30T12:11:35 IST">
  <testcase classname="api.testData.UserTest" name="test_PostUser" time="0.008">
    <failure type="java.lang.IllegalAccessError" message="class api.testData.UserTest (in unnamed module @0x4520ebad) cannot access class jdk.internal.org.jline.utils.Log (in module jdk.internal.le) because module jdk.internal.le does not export jdk.internal.org.jline.utils to unnamed module @0x4520ebad">
      <![CDATA[java.lang.IllegalAccessError: class api.testData.UserTest (in unnamed module @0x4520ebad) cannot access class jdk.internal.org.jline.utils.Log (in module jdk.internal.le) because module jdk.internal.le does not export jdk.internal.org.jline.utils to unnamed module @0x4520ebad
at api.testData.UserTest.test_PostUser(UserTest.java:52)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test_PostUser -->
  <testcase classname="api.testData.UserTest" name="test_GetUserByName" time="3.042">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;404&amp;gt; but was:&amp;lt;200&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<404> but was:<200>
at api.testData.UserTest.test_GetUserByName(UserTest.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test_GetUserByName -->
  <testcase classname="api.testData.UserTest" name="test_UpdateUserByName" time="4.989"/>
  <testcase classname="api.testData.UserTest" name="test_DeleteUserByName" time="1.604"/>
</testsuite> <!-- Test -->
